### ISSUE TITLE
Explanation about the hook folder and its content use

### ISSUE THREAD

**Issue by EyalBrilling** [gazebosim/ros_gz_project_template#16]
It isn't clear what the hooks folder is used for.
Additional explanation about "ament_environment_hooks" would also be helpful.
If i didn't miss anything, the only doc about it is in the ["ROS 2 and Gazebo Integration Best Practices"](https://vimeo.com/showcase/9954564/video/767127300) video at around 11:00.

I will be happy to add this documnataion myself but need more experience with it first. can put me as assignee.
If there are pointers to where to add the explanation that will be helpful(at the files themself/readme or somewhere else)

**Comment by mjcarroll** [comment]
The`ament_environment_hooks` is a feature of `ament` that allows users to set arbitrary environment variables as part of sourcing the environment.

In practice, this means that variables that are set in that folder are set when you call `setup.sh` or are set when dependent packages are being built.

These are populated and installed as part of these function calls: https://github.com/gazebosim/ros_gz_project_template/blob/b7bf3d589f751e492fdbbd9da2030ddcd6c66762/ros_gz_example_gazebo/CMakeLists.txt#L98-L103 where the `.in` suffix causes them to be pre-processed by CMake's [configure_file](https://cmake.org/cmake/help/latest/command/configure_file.html) call.

The actual implementation of `ament_environment_hook` is [here](https://github.com/ament/ament_cmake/blob/master/ament_cmake_core/cmake/environment_hooks/ament_environment_hooks.cmake#L27) if that is also helpful in understanding.

Specifically for this project, we set the environment variables

* `GZ_SIM_RESOURCE_PATH` - this appends the paths to world and model files such Gazebo can find them at runtime
* `GZ_SIM_SYSTEM_PLUGIN_PATH` - this appends the paths to system plugin shared libraries such that Gazebo can find them at runtime.

The two template files are:

* `.sh` - This will be evaluated by linux/macOS shells (sh, bash, zsh, etc).
* `.dsv` - This is a machine-readable format of the expected environment changes that ament will take advantage of for performance (faster than sourcing shell scripts, in general).  You can read more about this here: https://github.com/ament/ament_cmake/pull/187 and here: https://github.com/ros2/ros2/issues/764


I think you could add a README.md in the hooks directory, which would help clarify this?

**Comment by cord-burmeister** [comment]
I am new to ROS and the community and try to catch up with all the information. Trying to adapt the template information which requires a lot of information when starting. 
Found the pull request and found it very helpful.
